[opener]
edit = [
  { run = 'nvim "$@"', block = true, for = "unix" },
]
# image = [
#   { run = 'imv "$@"', block = false, orphan = true, desc = "imv" },
# ]
# document = [
#   { run = 'zathura "$@"', block = false, orphan = true, desc = "zathura" },
# ]
#
# [open]
# rules = [
#   { mime = "text/*", use = "edit" },
#   { mime = "application/json", use = "edit" },
#   { mime = "application/x-sh", use = "edit" },
#   { mime = "image/*", use = "image" },
#   { mime = "application/pdf", use = "document" },
#   { mime = "application/epub+zip", use = "document" },
#   { mime = "application/x-cbr", use = "document" },
#   { mime = "application/x-cbz", use = "document" },
#   { mime = "image/vnd.djvu", use = "document" },
# ]

[tasks]
image_bound      = [ 20000, 20000 ]

